import { mkdir, rm, cp, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export interface ExtensionInstallOptions {
  /** Install into the global pi agent directory instead of the current project. */
  global?: boolean;
  /** Install into the current project's .pi directory (default). */
  project?: boolean;
  /** Override the base .pi directory (defaults to ~/.pi/agent or ./.pi). */
  piDir?: string;
}

const SHIM = `// Auto-generated by \`npx @mfittko/repo-wiki extension install\`
import repoWiki from '@mfittko/repo-wiki/extension';

export default repoWiki;
`;

export async function runExtensionInstall(options: ExtensionInstallOptions = {}) {
  const cwd = process.cwd();
  const baseDir: string = (() => {
    if (options.piDir) {
      return path.resolve(options.piDir);
    }
    if (options.global) {
      return path.resolve(os.homedir(), '.pi/agent');
    }
    return path.resolve(cwd, '.pi');
  })();

  const extensionsDir = path.join(baseDir, 'extensions');
  const skillsDir = path.join(baseDir, 'skills');

  const currentFile = fileURLToPath(import.meta.url);
  // dist/src/extension-install.js -> dist -> package root
  const packageRoot = path.resolve(path.dirname(currentFile), '../..');
  const skillSource = path.join(packageRoot, 'skills', 'repo-wiki-cli');

  await mkdir(extensionsDir, { recursive: true });
  await mkdir(skillsDir, { recursive: true });

  const shimPath = path.join(extensionsDir, 'repo-wiki.ts');
  await writeFile(shimPath, SHIM, 'utf8');

  const skillDestination = path.join(skillsDir, 'repo-wiki-cli');
  await rm(skillDestination, { recursive: true, force: true });
  await cp(skillSource, skillDestination, { recursive: true, preserveTimestamps: true, force: true });

  const summary = {
    installed: true,
    scope: options.global ? 'global' : options.project ? 'project' : 'project',
    shim: shimPath,
    skill: skillDestination,
    reloadHint: 'Run `pi`, then `/reload` to load the repo-wiki extension.',
  };

  console.log(JSON.stringify(summary, null, 2));
}
