import { mkdir, rm, cp, writeFile, stat } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export interface ExtensionInstallOptions {
  /** Install into the global pi agent directory instead of the current project. */
  global?: boolean;
  /** Install into the current project's .pi directory (default). */
  project?: boolean;
  /** Override the base .pi directory (defaults to ~/.pi/agent or ./.pi). */
  piDir?: string;
  /** Overwrite an existing shim and skill destination. Defaults to false. */
  force?: boolean;
}

const SHIM = `// Auto-generated by \`npx @mfittko/repo-wiki extension install\`
import repoWiki from '@mfittko/repo-wiki/extension';

export default repoWiki;
`;

export async function runExtensionInstall(options: ExtensionInstallOptions = {}) {
  if (options.global && options.project) {
    const err = new Error('Cannot use --global and --project together; choose one.');
    (err as Error & { code?: string }).code = 'EXT_INSTALL_SCOPE_CONFLICT';
    throw err;
  }
  const cwd = process.cwd();
  const baseDir: string = (() => {
    if (options.piDir) {
      return path.resolve(options.piDir);
    }
    if (options.global) {
      return path.resolve(os.homedir(), '.pi/agent');
    }
    return path.resolve(cwd, '.pi');
  })();

  const extensionsDir = path.join(baseDir, 'extensions');
  const skillsDir = path.join(baseDir, 'skills');

  const currentFile = fileURLToPath(import.meta.url);
  // dist/src/extension-install.js -> dist -> package root
  const packageRoot = path.resolve(path.dirname(currentFile), '../..');
  const skillSource = path.join(packageRoot, 'skills', 'repo-wiki-cli');

  await mkdir(extensionsDir, { recursive: true });
  await mkdir(skillsDir, { recursive: true });

  const shimPath = path.join(extensionsDir, 'repo-wiki.ts');
  const skillDestination = path.join(skillsDir, 'repo-wiki-cli');

  // Refuse to clobber existing paths unless --force is set.
  const collisions: string[] = [];
  try {
    await stat(shimPath);
    collisions.push(shimPath);
  } catch {
    // missing, fine
  }
  try {
    await stat(skillDestination);
    collisions.push(skillDestination);
  } catch {
    // missing, fine
  }
  if (collisions.length > 0 && !options.force) {
    const message = `Refusing to overwrite existing path(s):\n${collisions.join('\n')}\nRe-run with \`--force\` to replace.`;
    const err = new Error(message);
    (err as Error & { code?: string }).code = 'EXT_INSTALL_COLLISION';
    throw err;
  }

  await writeFile(shimPath, SHIM, 'utf8');

  await rm(skillDestination, { recursive: true, force: true });
  await cp(skillSource, skillDestination, { recursive: true, preserveTimestamps: true, force: true });

  const summary = {
    installed: true,
    scope: options.global ? 'global' : options.project ? 'project' : options.piDir ? 'custom' : 'project',
    shim: shimPath,
    skill: skillDestination,
    reloadHint: 'Run `pi`, then `/reload` to load the repo-wiki extension.',
  };

  console.log(JSON.stringify(summary, null, 2));
}
