/**
 * LLM provider boundary for wiki synthesis.
 *
 * Defines provider request/response interfaces, structured error handling,
 * a deterministic mock provider for tests and local CI, and a factory that
 * selects the correct provider from configuration.
 *
 * Usage (tests / CI without network):
 *   const provider = createProvider();                  // defaults to mock
 *   const provider = createProvider({ provider: 'mock' });
 *
 * Usage (future hosted provider, not yet implemented):
 *   const provider = createProvider({ provider: 'openai', apiKey: '...' });
 */

import { type PageArchetype, type PromptContext, buildPrompt } from './prompts.js';

export type { PageArchetype };
export type { PromptContext };

// ── Request / response shapes ──────────────────────────────────────────────

/** Input sent to an LLM provider for a single wiki page synthesis. */
export interface LLMRequest {
  /** Page archetype that selected the prompt template. */
  archetype: PageArchetype;
  /** Kebab-case page identifier without .md (e.g. "Module-Auth"). */
  pageName: string;
  /** Human-readable page title (e.g. "Auth"). */
  pageTitle: string;
  /** System-level instructions (authority rules, output contract). */
  systemPrompt: string;
  /** Page-specific user prompt including source cards and context. */
  userPrompt: string;
  /** Optional token budget for the completion. */
  maxTokens?: number;
}

/** Output returned by an LLM provider after synthesis. */
export interface LLMResponse {
  /** Generated markdown page content. */
  content: string;
  /** Identifier of the provider that produced the response. */
  provider: string;
  /** Prompt tokens consumed (informational; may be undefined for mock). */
  promptTokens?: number;
  /** Completion tokens consumed (informational; may be undefined for mock). */
  completionTokens?: number;
}

// ── Provider interface ─────────────────────────────────────────────────────

/** Common interface every LLM backend must implement. */
export interface LLMProvider {
  /** Stable identifier for logging and frontmatter. */
  readonly name: string;
  /**
   * Synthesise wiki page content for the given request.
   * Throws `LLMProviderError` on unrecoverable failure.
   */
  complete(request: LLMRequest): Promise<LLMResponse>;
}

// ── Structured error ───────────────────────────────────────────────────────

/**
 * Thrown by providers and the factory for all LLM-related failures.
 *
 *   try { … } catch (err) {
 *     if (err instanceof LLMProviderError && err.retryable) { … }
 *   }
 */
export class LLMProviderError extends Error {
  /** Identifier of the provider that raised the error. */
  readonly provider: string;
  /** Machine-readable code (e.g. 'MISSING_API_KEY', 'RATE_LIMIT'). */
  readonly code: string | undefined;
  /** True when the call may be retried after a short back-off. */
  readonly retryable: boolean;

  constructor(message: string, provider: string, code?: string, retryable = false) {
    super(message);
    this.name = 'LLMProviderError';
    this.provider = provider;
    this.code = code;
    this.retryable = retryable;
  }
}

// ── Mock provider (deterministic, no network) ──────────────────────────────

/**
 * Deterministic provider for tests and local CI.
 * Returns a minimal, reproducible markdown page for any request without
 * making network calls or requiring API credentials.
 */
export class MockLLMProvider implements LLMProvider {
  readonly name = 'mock';

  async complete(request: LLMRequest): Promise<LLMResponse> {
    return { content: buildMockContent(request), provider: this.name };
  }
}

function buildMockContent(request: LLMRequest): string {
  const lines: string[] = [
    '---',
    `page_type: ${JSON.stringify(request.archetype)}`,
    `page_name: ${JSON.stringify(request.pageName)}`,
    `compiled_at: "mock"`,
    `source_commit: "mock"`,
    `source_paths: []`,
    '---',
    '',
    `# ${request.pageTitle}`,
    '',
    '> Generated by the mock LLM provider (deterministic, no network).',
    '',
    `**Archetype:** ${request.archetype}`,
    '',
  ];

  if (request.archetype === 'module') {
    lines.push('<!-- HUMAN_NOTES_START -->');
    lines.push('<!-- HUMAN_NOTES_END -->');
    lines.push('');
  }

  return lines.join('\n');
}

// ── Provider configuration ─────────────────────────────────────────────────

/** Configuration passed to `createProvider`. */
export interface LLMProviderConfig {
  /**
   * Provider identifier.
   * Defaults to `"mock"` so that tests and non-LLM runs work without any
   * further configuration.
   */
  provider?: string;
  /** API key required by hosted providers. Not used by the mock provider. */
  apiKey?: string;
  /** Model identifier passed to hosted providers. */
  model?: string;
  /** Optional base URL override for self-hosted or proxy endpoints. */
  baseUrl?: string;
}

// ── Factory ────────────────────────────────────────────────────────────────

/**
 * Create an `LLMProvider` from explicit configuration.
 *
 * - Omitting `config` (or setting `provider: "mock"`) returns the mock provider.
 * - Specifying an unknown provider without an API key throws
 *   `LLMProviderError` with `code: "MISSING_API_KEY"`.
 * - Specifying an unknown provider name throws
 *   `LLMProviderError` with `code: "UNKNOWN_PROVIDER"`.
 *
 * This makes missing configuration fail loudly rather than silently falling
 * back to an unexpected behaviour.
 */
export function createProvider(config: LLMProviderConfig = {}): LLMProvider {
  const providerName = config.provider ?? 'mock';

  if (providerName === 'mock') {
    return new MockLLMProvider();
  }

  if (!config.apiKey) {
    throw new LLMProviderError(
      `Provider "${providerName}" requires an API key. ` +
        `Set apiKey in the provider config, or use provider="mock" for tests and CI.`,
      providerName,
      'MISSING_API_KEY',
    );
  }

  // Hosted provider implementations will be added here in future issues.
  throw new LLMProviderError(
    `Unknown provider: "${providerName}". Supported providers: mock.`,
    providerName,
    'UNKNOWN_PROVIDER',
  );
}

// ── Convenience builder ────────────────────────────────────────────────────

/**
 * Assemble an `LLMRequest` from a `PromptContext` using the standard prompt
 * templates.  Callers can then pass the result directly to
 * `provider.complete(request)`.
 *
 * @param archetype  - Page archetype that selects the prompt template.
 * @param context    - Assembled page context (source cards, doc cards, etc.).
 * @param maxTokens  - Optional completion-token budget for the provider.
 *                     When omitted the provider uses its own default limit.
 *                     Typical values: 2048 for module pages, 4096 for
 *                     foundation pages.  Check your provider's documentation
 *                     for valid ranges.
 */
export function buildRequest(
  archetype: PageArchetype,
  context: PromptContext,
  maxTokens?: number,
): LLMRequest {
  const prompt = buildPrompt(archetype, context);
  return {
    archetype,
    pageName: context.pageName,
    pageTitle: context.pageTitle,
    systemPrompt: prompt.system,
    userPrompt: prompt.user,
    maxTokens,
  };
}
